const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const mongoose = require('mongoose');
require('dotenv').config({ path: './config/.env.local' });
const articles = require('./routes/article');
mongoose.connect(process.env.MONGO_URI);
var app = express();
app.use(cors());
app.use(bodyParser.urlencoded({extended : true}));
app.use(express.json());
app.use('/articles', articles);
app.listen(process.env.PORT);